import './config/root'
import './uiBuilderLegacy/index'
import './basic/index'
import './warps/index'
import './homes/index'
import './ranks/index'
import './shop/root'
import './platformSettings/index'
import './clans/index'
import './customCommands/index'
import './UIBuilderV2/index'
import './sidebar/index'
import './economy/index'
import './moderation/index'
// import './test'

// import all index in folders