let vanillaPack = {
    page1: {
        namespace: "vanilla",
        nextPack: "vanilla2",
        icons: [
            {name: "acacia_chest_boat", path: "textures/items/acacia_chest_boat.png"},
            {name: "acacia_hanging_sign", path: "textures/items/acacia_hanging_sign.png"},
            {name: "amethyst_shard", path: "textures/items/amethyst_shard.png"},
            {name: "angler_pottery_sherd", path: "textures/items/angler_pottery_sherd.png"},
            {name: "apple", path: "textures/items/apple.png"},
            {name: "apple_golden", path: "textures/items/apple_golden.png"},
            {name: "archer_pottery_sherd", path: "textures/items/archer_pottery_sherd.png"},
            {name: "armadillo_scute", path: "textures/items/armadillo_scute.png"},
            {name: "armor_stand", path: "textures/items/armor_stand.png"},
            {name: "arms_up_pottery_sherd", path: "textures/items/arms_up_pottery_sherd.png"},
            {name: "arrow", path: "textures/items/arrow.png"},
            {name: "bamboo", path: "textures/items/bamboo.png"},
            {name: "bamboo_chest_raft", path: "textures/items/bamboo_chest_raft.png"},
            {name: "bamboo_door", path: "textures/items/bamboo_door.png"},
            {name: "bamboo_hanging_sign", path: "textures/items/bamboo_hanging_sign.png"},
            {name: "bamboo_raft", path: "textures/items/bamboo_raft.png"},
            {name: "bamboo_sign", path: "textures/items/bamboo_sign.png"},
            {name: "banner_pattern", path: "textures/items/banner_pattern.png"},
            {name: "bed_black", path: "textures/items/bed_black.png"},
            {name: "bed_blue", path: "textures/items/bed_blue.png"},
            {name: "bed_brown", path: "textures/items/bed_brown.png"},
            {name: "bed_cyan", path: "textures/items/bed_cyan.png"},
            {name: "bed_gray", path: "textures/items/bed_gray.png"},
            {name: "bed_green", path: "textures/items/bed_green.png"},
            {name: "bed_light_blue", path: "textures/items/bed_light_blue.png"},
            {name: "bed_lime", path: "textures/items/bed_lime.png"},
            {name: "bed_magenta", path: "textures/items/bed_magenta.png"},
            {name: "bed_orange", path: "textures/items/bed_orange.png"},
            {name: "bed_pink", path: "textures/items/bed_pink.png"},
            {name: "bed_purple", path: "textures/items/bed_purple.png"},
            {name: "bed_red", path: "textures/items/bed_red.png"},
            {name: "bed_silver", path: "textures/items/bed_silver.png"},
            {name: "bed_white", path: "textures/items/bed_white.png"},
            {name: "bed_yellow", path: "textures/items/bed_yellow.png"},
            {name: "beef_cooked", path: "textures/items/beef_cooked.png"},
            {name: "beef_raw", path: "textures/items/beef_raw.png"},
            {name: "beetroot", path: "textures/items/beetroot.png"},
            {name: "beetroot_soup", path: "textures/items/beetroot_soup.png"},
            {name: "birch_chest_boat", path: "textures/items/birch_chest_boat.png"},
            {name: "birch_hanging_sign", path: "textures/items/birch_hanging_sign.png"},
            {name: "blade_pottery_sherd", path: "textures/items/blade_pottery_sherd.png"},
            {name: "blaze_powder", path: "textures/items/blaze_powder.png"},
            {name: "blaze_rod", path: "textures/items/blaze_rod.png"},
            {name: "boat", path: "textures/items/boat.png"},
            {name: "boat_acacia", path: "textures/items/boat_acacia.png"}
        ],
        previousPack: 'azalea_old'
    },
    page2: {
        namespace: "vanilla",
        nextPack: "vanilla3",
        icons: [
            {name: "boat_birch", path: "textures/items/boat_birch.png"},
            {name: "boat_darkoak", path: "textures/items/boat_darkoak.png"},
            {name: "boat_dark_oak", path: "textures/items/boat_dark_oak.png"},
            {name: "boat_jungle", path: "textures/items/boat_jungle.png"},
            {name: "boat_oak", path: "textures/items/boat_oak.png"},
            {name: "boat_spruce", path: "textures/items/boat_spruce.png"},
            {name: "bolt_armor_trim_smithing_template", path: "textures/items/bolt_armor_trim_smithing_template.png"},
            {name: "bone", path: "textures/items/bone.png"},
            {name: "book_enchanted", path: "textures/items/book_enchanted.png"},
            {name: "book_normal", path: "textures/items/book_normal.png"},
            {name: "book_portfolio", path: "textures/items/book_portfolio.png"},
            {name: "book_writable", path: "textures/items/book_writable.png"},
            {name: "book_written", path: "textures/items/book_written.png"},
            {name: "bordure_indented_banner_pattern", path: "textures/items/bordure_indented_banner_pattern.png"},
            {name: "bowl", path: "textures/items/bowl.png"},
            {name: "bow_pulling_0", path: "textures/items/bow_pulling_0.png"},
            {name: "bow_pulling_1", path: "textures/items/bow_pulling_1.png"},
            {name: "bow_pulling_2", path: "textures/items/bow_pulling_2.png"},
            {name: "bow_standby", path: "textures/items/bow_standby.png"},
            {name: "bread", path: "textures/items/bread.png"},
            {name: "breeze_rod", path: "textures/items/breeze_rod.png"},
            {name: "brewer_pottery_sherd", path: "textures/items/brewer_pottery_sherd.png"},
            {name: "brewing_stand", path: "textures/items/brewing_stand.png"},
            {name: "brick", path: "textures/items/brick.png"},
            {name: "broken_elytra", path: "textures/items/broken_elytra.png"},
            {name: "brush", path: "textures/items/brush.png"},
            {name: "bucket_axolotl", path: "textures/items/bucket_axolotl.png"},
            {name: "bucket_cod", path: "textures/items/bucket_cod.png"},
            {name: "bucket_empty", path: "textures/items/bucket_empty.png"},
            {name: "bucket_lava", path: "textures/items/bucket_lava.png"},
            {name: "bucket_milk", path: "textures/items/bucket_milk.png"},
            {name: "bucket_powder_snow", path: "textures/items/bucket_powder_snow.png"},
            {name: "bucket_pufferfish", path: "textures/items/bucket_pufferfish.png"},
            {name: "bucket_salmon", path: "textures/items/bucket_salmon.png"},
            {name: "bucket_tadpole", path: "textures/items/bucket_tadpole.png"},
            {name: "bucket_tropical", path: "textures/items/bucket_tropical.png"},
            {name: "bucket_water", path: "textures/items/bucket_water.png"},
            {name: "bundle", path: "textures/items/bundle.png"},
            {name: "bundle_black", path: "textures/items/bundle_black.png"},
            {name: "bundle_black_open", path: "textures/items/bundle_black_open.png"},
            {name: "bundle_black_open_back", path: "textures/items/bundle_black_open_back.png"},
            {name: "bundle_black_open_front", path: "textures/items/bundle_black_open_front.png"},
            {name: "bundle_blue", path: "textures/items/bundle_blue.png"},
            {name: "bundle_blue_open", path: "textures/items/bundle_blue_open.png"},
            {name: "bundle_blue_open_back", path: "textures/items/bundle_blue_open_back.png"}
        ],
        previousPack: 'vanilla'
    },
    page3: {
        namespace: "vanilla",
        nextPack: "vanilla4",
        icons: [
            {name: "bundle_blue_open_front", path: "textures/items/bundle_blue_open_front.png"},
            {name: "bundle_brown", path: "textures/items/bundle_brown.png"},
            {name: "bundle_brown_open", path: "textures/items/bundle_brown_open.png"},
            {name: "bundle_brown_open_back", path: "textures/items/bundle_brown_open_back.png"},
            {name: "bundle_brown_open_front", path: "textures/items/bundle_brown_open_front.png"},
            {name: "bundle_cyan", path: "textures/items/bundle_cyan.png"},
            {name: "bundle_cyan_open", path: "textures/items/bundle_cyan_open.png"},
            {name: "bundle_cyan_open_back", path: "textures/items/bundle_cyan_open_back.png"},
            {name: "bundle_cyan_open_front", path: "textures/items/bundle_cyan_open_front.png"},
            {name: "bundle_gray", path: "textures/items/bundle_gray.png"},
            {name: "bundle_gray_open", path: "textures/items/bundle_gray_open.png"},
            {name: "bundle_gray_open_back", path: "textures/items/bundle_gray_open_back.png"},
            {name: "bundle_gray_open_front", path: "textures/items/bundle_gray_open_front.png"},
            {name: "bundle_green", path: "textures/items/bundle_green.png"},
            {name: "bundle_green_open", path: "textures/items/bundle_green_open.png"},
            {name: "bundle_green_open_back", path: "textures/items/bundle_green_open_back.png"},
            {name: "bundle_green_open_front", path: "textures/items/bundle_green_open_front.png"},
            {name: "bundle_light_blue", path: "textures/items/bundle_light_blue.png"},
            {name: "bundle_light_blue_open", path: "textures/items/bundle_light_blue_open.png"},
            {name: "bundle_light_blue_open_back", path: "textures/items/bundle_light_blue_open_back.png"},
            {name: "bundle_light_blue_open_front", path: "textures/items/bundle_light_blue_open_front.png"},
            {name: "bundle_light_gray", path: "textures/items/bundle_light_gray.png"},
            {name: "bundle_light_gray_open", path: "textures/items/bundle_light_gray_open.png"},
            {name: "bundle_light_gray_open_back", path: "textures/items/bundle_light_gray_open_back.png"},
            {name: "bundle_light_gray_open_front", path: "textures/items/bundle_light_gray_open_front.png"},
            {name: "bundle_lime", path: "textures/items/bundle_lime.png"},
            {name: "bundle_lime_open", path: "textures/items/bundle_lime_open.png"},
            {name: "bundle_lime_open_back", path: "textures/items/bundle_lime_open_back.png"},
            {name: "bundle_lime_open_front", path: "textures/items/bundle_lime_open_front.png"},
            {name: "bundle_magenta", path: "textures/items/bundle_magenta.png"},
            {name: "bundle_magenta_open", path: "textures/items/bundle_magenta_open.png"},
            {name: "bundle_magenta_open_back", path: "textures/items/bundle_magenta_open_back.png"},
            {name: "bundle_magenta_open_front", path: "textures/items/bundle_magenta_open_front.png"},
            {name: "bundle_open", path: "textures/items/bundle_open.png"},
            {name: "bundle_open_back", path: "textures/items/bundle_open_back.png"},
            {name: "bundle_open_front", path: "textures/items/bundle_open_front.png"},
            {name: "bundle_orange", path: "textures/items/bundle_orange.png"},
            {name: "bundle_orange_open", path: "textures/items/bundle_orange_open.png"},
            {name: "bundle_orange_open_back", path: "textures/items/bundle_orange_open_back.png"},
            {name: "bundle_orange_open_front", path: "textures/items/bundle_orange_open_front.png"},
            {name: "bundle_pink", path: "textures/items/bundle_pink.png"},
            {name: "bundle_pink_open", path: "textures/items/bundle_pink_open.png"},
            {name: "bundle_pink_open_back", path: "textures/items/bundle_pink_open_back.png"},
            {name: "bundle_pink_open_front", path: "textures/items/bundle_pink_open_front.png"},
            {name: "bundle_purple", path: "textures/items/bundle_purple.png"}
        ],
        previousPack: 'vanilla2'
    },
    page4: {
        namespace: "vanilla",
        nextPack: 'vanilla5',
        previousPack: 'vanilla3',
        icons: [
            {name: "bundle_purple_open", path: "textures/items/bundle_purple_open.png"},
            {name: "bundle_purple_open_back", path: "textures/items/bundle_purple_open_back.png"},
            {name: "bundle_purple_open_front", path: "textures/items/bundle_purple_open_front.png"},
            {name: "bundle_red", path: "textures/items/bundle_red.png"},
            {name: "bundle_red_open", path: "textures/items/bundle_red_open.png"},
            {name: "bundle_red_open_back", path: "textures/items/bundle_red_open_back.png"},
            {name: "bundle_red_open_front", path: "textures/items/bundle_red_open_front.png"},
            {name: "bundle_white", path: "textures/items/bundle_white.png"},
            {name: "bundle_white_open", path: "textures/items/bundle_white_open.png"},
            {name: "bundle_white_open_back", path: "textures/items/bundle_white_open_back.png"},
            {name: "bundle_white_open_front", path: "textures/items/bundle_white_open_front.png"},
            {name: "bundle_yellow", path: "textures/items/bundle_yellow.png"},
            {name: "bundle_yellow_open", path: "textures/items/bundle_yellow_open.png"},
            {name: "bundle_yellow_open_back", path: "textures/items/bundle_yellow_open_back.png"},
            {name: "bundle_yellow_open_front", path: "textures/items/bundle_yellow_open_front.png"},
            {name: "burn_pottery_sherd", path: "textures/items/burn_pottery_sherd.png"},
            {name: "cake", path: "textures/items/cake.png"},
            {name: "campfire", path: "textures/items/campfire.png"},
            {name: "carrot", path: "textures/items/carrot.png"},
            {name: "carrot_golden", path: "textures/items/carrot_golden.png"},
            {name: "carrot_on_a_stick", path: "textures/items/carrot_on_a_stick.png"},
            {name: "cauldron", path: "textures/items/cauldron.png"},
            {name: "chain", path: "textures/items/chain.png"},
            {name: "chainmail_boots", path: "textures/items/chainmail_boots.png"},
            {name: "chainmail_chestplate", path: "textures/items/chainmail_chestplate.png"},
            {name: "chainmail_helmet", path: "textures/items/chainmail_helmet.png"},
            {name: "chainmail_leggings", path: "textures/items/chainmail_leggings.png"},
            {name: "chalkboard_large", path: "textures/items/chalkboard_large.png"},
            {name: "chalkboard_medium", path: "textures/items/chalkboard_medium.png"},
            {name: "chalkboard_small", path: "textures/items/chalkboard_small.png"},
            {name: "charcoal", path: "textures/items/charcoal.png"},
            {name: "cherry_boat", path: "textures/items/cherry_boat.png"},
            {name: "cherry_chest_boat", path: "textures/items/cherry_chest_boat.png"},
            {name: "cherry_door", path: "textures/items/cherry_door.png"},
            {name: "cherry_hanging_sign", path: "textures/items/cherry_hanging_sign.png"},
            {name: "cherry_sign", path: "textures/items/cherry_sign.png"},
            {name: "chicken_cooked", path: "textures/items/chicken_cooked.png"},
            {name: "chicken_raw", path: "textures/items/chicken_raw.png"},
            {name: "chorus_fruit", path: "textures/items/chorus_fruit.png"},
            {name: "chorus_fruit_popped", path: "textures/items/chorus_fruit_popped.png"},
            {name: "clay_ball", path: "textures/items/clay_ball.png"},
            {name: "clock_item", path: "textures/items/clock_item.png"},
            {name: "coal", path: "textures/items/coal.png"},
            {name: "coast_armor_trim_smithing_template", path: "textures/items/coast_armor_trim_smithing_template.png"},
            {name: "comparator", path: "textures/items/comparator.png"}
        ]
    },
    page5: {
        namespace: "vanilla",
        nextPack: 'vanilla6',
        previousPack: 'vanilla4',
        icons: [
            {name: "compass_atlas", path: "textures/items/compass_atlas.png"},
            {name: "compass_item", path: "textures/items/compass_item.png"},
            {name: "cookie", path: "textures/items/cookie.png"},
            {name: "copper_door", path: "textures/items/copper_door.png"},
            {name: "copper_ingot", path: "textures/items/copper_ingot.png"},
            {name: "creeper_banner_pattern", path: "textures/items/creeper_banner_pattern.png"},
            {name: "crimson_door", path: "textures/items/crimson_door.png"},
            {name: "crimson_hanging_sign", path: "textures/items/crimson_hanging_sign.png"},
            {name: "crossbow_arrow", path: "textures/items/crossbow_arrow.png"},
            {name: "crossbow_firework", path: "textures/items/crossbow_firework.png"},
            {name: "crossbow_pulling_0", path: "textures/items/crossbow_pulling_0.png"},
            {name: "crossbow_pulling_1", path: "textures/items/crossbow_pulling_1.png"},
            {name: "crossbow_pulling_2", path: "textures/items/crossbow_pulling_2.png"},
            {name: "crossbow_standby", path: "textures/items/crossbow_standby.png"},
            {name: "danger_pottery_sherd", path: "textures/items/danger_pottery_sherd.png"},
            {name: "dark_oak_chest_boat", path: "textures/items/dark_oak_chest_boat.png"},
            {name: "dark_oak_hanging_sign", path: "textures/items/dark_oak_hanging_sign.png"},
            {name: "diamond", path: "textures/items/diamond.png"},
            {name: "diamond_axe", path: "textures/items/diamond_axe.png"},
            {name: "diamond_boots", path: "textures/items/diamond_boots.png"},
            {name: "diamond_chestplate", path: "textures/items/diamond_chestplate.png"},
            {name: "diamond_helmet", path: "textures/items/diamond_helmet.png"},
            {name: "diamond_hoe", path: "textures/items/diamond_hoe.png"},
            {name: "diamond_horse_armor", path: "textures/items/diamond_horse_armor.png"},
            {name: "diamond_leggings", path: "textures/items/diamond_leggings.png"},
            {name: "diamond_pickaxe", path: "textures/items/diamond_pickaxe.png"},
            {name: "diamond_shovel", path: "textures/items/diamond_shovel.png"},
            {name: "diamond_sword", path: "textures/items/diamond_sword.png"},
            {name: "disc_fragment_5", path: "textures/items/disc_fragment_5.png"},
            {name: "door_acacia", path: "textures/items/door_acacia.png"},
            {name: "door_birch", path: "textures/items/door_birch.png"},
            {name: "door_dark_oak", path: "textures/items/door_dark_oak.png"},
            {name: "door_iron", path: "textures/items/door_iron.png"},
            {name: "door_jungle", path: "textures/items/door_jungle.png"},
            {name: "door_spruce", path: "textures/items/door_spruce.png"},
            {name: "door_wood", path: "textures/items/door_wood.png"},
            {name: "dragons_breath", path: "textures/items/dragons_breath.png"},
            {name: "dragon_fireball", path: "textures/items/dragon_fireball.png"},
            {name: "dried_kelp", path: "textures/items/dried_kelp.png"},
            {name: "dune_armor_trim_smithing_template", path: "textures/items/dune_armor_trim_smithing_template.png"},
            {name: "dye_powder_black", path: "textures/items/dye_powder_black.png"},
            {name: "dye_powder_black_new", path: "textures/items/dye_powder_black_new.png"},
            {name: "dye_powder_blue", path: "textures/items/dye_powder_blue.png"},
            {name: "dye_powder_blue_new", path: "textures/items/dye_powder_blue_new.png"},
            {name: "dye_powder_brown", path: "textures/items/dye_powder_brown.png"}
        ]
    },
    page6: {
        namespace: "vanilla",
        nextPack: 'vanilla7',
        previousPack: 'vanilla5',
        icons: [
            {name: "dye_powder_brown_new", path: "textures/items/dye_powder_brown_new.png"},
            {name: "dye_powder_cyan", path: "textures/items/dye_powder_cyan.png"},
            {name: "dye_powder_glow", path: "textures/items/dye_powder_glow.png"},
            {name: "dye_powder_gray", path: "textures/items/dye_powder_gray.png"},
            {name: "dye_powder_green", path: "textures/items/dye_powder_green.png"},
            {name: "dye_powder_light_blue", path: "textures/items/dye_powder_light_blue.png"},
            {name: "dye_powder_lime", path: "textures/items/dye_powder_lime.png"},
            {name: "dye_powder_magenta", path: "textures/items/dye_powder_magenta.png"},
            {name: "dye_powder_orange", path: "textures/items/dye_powder_orange.png"},
            {name: "dye_powder_pink", path: "textures/items/dye_powder_pink.png"},
            {name: "dye_powder_purple", path: "textures/items/dye_powder_purple.png"},
            {name: "dye_powder_red", path: "textures/items/dye_powder_red.png"},
            {name: "dye_powder_silver", path: "textures/items/dye_powder_silver.png"},
            {name: "dye_powder_white", path: "textures/items/dye_powder_white.png"},
            {name: "dye_powder_white_new", path: "textures/items/dye_powder_white_new.png"},
            {name: "dye_powder_yellow", path: "textures/items/dye_powder_yellow.png"},
            {name: "echo_shard", path: "textures/items/echo_shard.png"},
            {name: "egg", path: "textures/items/egg.png"},
            {name: "egg_agent", path: "textures/items/egg_agent.png"},
            {name: "egg_bat", path: "textures/items/egg_bat.png"},
            {name: "egg_bee", path: "textures/items/egg_bee.png"},
            {name: "egg_blaze", path: "textures/items/egg_blaze.png"},
            {name: "egg_cat", path: "textures/items/egg_cat.png"},
            {name: "egg_cave_spider", path: "textures/items/egg_cave_spider.png"},
            {name: "egg_chicken", path: "textures/items/egg_chicken.png"},
            {name: "egg_clownfish", path: "textures/items/egg_clownfish.png"},
            {name: "egg_cod", path: "textures/items/egg_cod.png"},
            {name: "egg_cow", path: "textures/items/egg_cow.png"},
            {name: "egg_creeper", path: "textures/items/egg_creeper.png"},
            {name: "egg_dolphin", path: "textures/items/egg_dolphin.png"},
            {name: "egg_donkey", path: "textures/items/egg_donkey.png"},
            {name: "egg_drowned", path: "textures/items/egg_drowned.png"},
            {name: "egg_elderguardian", path: "textures/items/egg_elderguardian.png"},
            {name: "egg_enderman", path: "textures/items/egg_enderman.png"},
            {name: "egg_endermite", path: "textures/items/egg_endermite.png"},
            {name: "egg_evoker", path: "textures/items/egg_evoker.png"},
            {name: "egg_fish", path: "textures/items/egg_fish.png"},
            {name: "egg_fox", path: "textures/items/egg_fox.png"},
            {name: "egg_ghast", path: "textures/items/egg_ghast.png"},
            {name: "egg_glow_squid", path: "textures/items/egg_glow_squid.png"},
            {name: "egg_guardian", path: "textures/items/egg_guardian.png"},
            {name: "egg_horse", path: "textures/items/egg_horse.png"},
            {name: "egg_husk", path: "textures/items/egg_husk.png"},
            {name: "egg_lava_slime", path: "textures/items/egg_lava_slime.png"},
            {name: "egg_llama", path: "textures/items/egg_llama.png"}
        ]
    },
    page7: {
        namespace: "vanilla",
        nextPack: 'vanilla8',
        previousPack: 'vanilla6',
        icons: [
            {name: "egg_mask", path: "textures/items/egg_mask.png"},
            {name: "egg_mule", path: "textures/items/egg_mule.png"},
            {name: "egg_mushroomcow", path: "textures/items/egg_mushroomcow.png"},
            {name: "egg_npc", path: "textures/items/egg_npc.png"},
            {name: "egg_null", path: "textures/items/egg_null.png"},
            {name: "egg_ocelot", path: "textures/items/egg_ocelot.png"},
            {name: "egg_panda", path: "textures/items/egg_panda.png"},
            {name: "egg_parrot", path: "textures/items/egg_parrot.png"},
            {name: "egg_phantom", path: "textures/items/egg_phantom.png"},
            {name: "egg_pig", path: "textures/items/egg_pig.png"},
            {name: "egg_pigzombie", path: "textures/items/egg_pigzombie.png"},
            {name: "egg_pillager", path: "textures/items/egg_pillager.png"},
            {name: "egg_polarbear", path: "textures/items/egg_polarbear.png"},
            {name: "egg_pufferfish", path: "textures/items/egg_pufferfish.png"},
            {name: "egg_rabbit", path: "textures/items/egg_rabbit.png"},
            {name: "egg_ravager", path: "textures/items/egg_ravager.png"},
            {name: "egg_salmon", path: "textures/items/egg_salmon.png"},
            {name: "egg_sheep", path: "textures/items/egg_sheep.png"},
            {name: "egg_shulker", path: "textures/items/egg_shulker.png"},
            {name: "egg_silverfish", path: "textures/items/egg_silverfish.png"},
            {name: "egg_skeleton", path: "textures/items/egg_skeleton.png"},
            {name: "egg_skeletonhorse", path: "textures/items/egg_skeletonhorse.png"},
            {name: "egg_slime", path: "textures/items/egg_slime.png"},
            {name: "egg_spider", path: "textures/items/egg_spider.png"},
            {name: "egg_squid", path: "textures/items/egg_squid.png"},
            {name: "egg_stray", path: "textures/items/egg_stray.png"},
            {name: "egg_turtle", path: "textures/items/egg_turtle.png"},
            {name: "egg_vex", path: "textures/items/egg_vex.png"},
            {name: "egg_villager", path: "textures/items/egg_villager.png"},
            {name: "egg_vindicator", path: "textures/items/egg_vindicator.png"},
            {name: "egg_wanderingtrader", path: "textures/items/egg_wanderingtrader.png"},
            {name: "egg_witch", path: "textures/items/egg_witch.png"},
            {name: "egg_wither", path: "textures/items/egg_wither.png"},
            {name: "egg_wolf", path: "textures/items/egg_wolf.png"},
            {name: "egg_zombie", path: "textures/items/egg_zombie.png"},
            {name: "egg_zombiehorse", path: "textures/items/egg_zombiehorse.png"},
            {name: "egg_zombievillager", path: "textures/items/egg_zombievillager.png"},
            {name: "elytra", path: "textures/items/elytra.png"},
            {name: "emerald", path: "textures/items/emerald.png"},
            {name: "empty_armor_slot_boots", path: "textures/items/empty_armor_slot_boots.png"},
            {name: "empty_armor_slot_chestplate", path: "textures/items/empty_armor_slot_chestplate.png"},
            {name: "empty_armor_slot_helmet", path: "textures/items/empty_armor_slot_helmet.png"},
            {name: "empty_armor_slot_leggings", path: "textures/items/empty_armor_slot_leggings.png"},
            {name: "empty_armor_slot_shield", path: "textures/items/empty_armor_slot_shield.png"},
            {name: "ender_eye", path: "textures/items/ender_eye.png"}
        ]
    },
    page8: {
        namespace: "vanilla",
        nextPack: 'vanilla9',
        previousPack: 'vanilla7',
        icons: [
            {name: "ender_pearl", path: "textures/items/ender_pearl.png"},
            {name: "end_crystal", path: "textures/items/end_crystal.png"},
            {name: "experience_bottle", path: "textures/items/experience_bottle.png"},
            {name: "explorer_pottery_sherd", path: "textures/items/explorer_pottery_sherd.png"},
            {name: "exposed_copper_door", path: "textures/items/exposed_copper_door.png"},
            {name: "eye_armor_trim_smithing_template", path: "textures/items/eye_armor_trim_smithing_template.png"},
            {name: "feather", path: "textures/items/feather.png"},
            {name: "field_masoned_banner_pattern", path: "textures/items/field_masoned_banner_pattern.png"},
            {name: "fireball", path: "textures/items/fireball.png"},
            {name: "fireworks", path: "textures/items/fireworks.png"},
            {name: "fishing_rod_cast", path: "textures/items/fishing_rod_cast.png"},
            {name: "fishing_rod_uncast", path: "textures/items/fishing_rod_uncast.png"},
            {name: "fish_clownfish_raw", path: "textures/items/fish_clownfish_raw.png"},
            {name: "fish_cooked", path: "textures/items/fish_cooked.png"},
            {name: "fish_pufferfish_raw", path: "textures/items/fish_pufferfish_raw.png"},
            {name: "fish_raw", path: "textures/items/fish_raw.png"},
            {name: "fish_salmon_cooked", path: "textures/items/fish_salmon_cooked.png"},
            {name: "fish_salmon_raw", path: "textures/items/fish_salmon_raw.png"},
            {name: "flint", path: "textures/items/flint.png"},
            {name: "flint_and_steel", path: "textures/items/flint_and_steel.png"},
            {name: "flower_banner_pattern", path: "textures/items/flower_banner_pattern.png"},
            {name: "flower_pot", path: "textures/items/flower_pot.png"},
            {name: "flow_armor_trim_smithing_template", path: "textures/items/flow_armor_trim_smithing_template.png"},
            {name: "flow_banner_pattern", path: "textures/items/flow_banner_pattern.png"},
            {name: "flow_pottery_sherd", path: "textures/items/flow_pottery_sherd.png"},
            {name: "friend_pottery_sherd", path: "textures/items/friend_pottery_sherd.png"},
            {name: "ghast_tear", path: "textures/items/ghast_tear.png"},
            {name: "globe_banner_pattern", path: "textures/items/globe_banner_pattern.png"},
            {name: "glowstone_dust", path: "textures/items/glowstone_dust.png"},
            {name: "glow_berries", path: "textures/items/glow_berries.png"},
            {name: "glow_item_frame", path: "textures/items/glow_item_frame.png"},
            {name: "goat_horn", path: "textures/items/goat_horn.png"},
            {name: "gold_axe", path: "textures/items/gold_axe.png"},
            {name: "gold_boots", path: "textures/items/gold_boots.png"},
            {name: "gold_chestplate", path: "textures/items/gold_chestplate.png"},
            {name: "gold_helmet", path: "textures/items/gold_helmet.png"},
            {name: "gold_hoe", path: "textures/items/gold_hoe.png"},
            {name: "gold_horse_armor", path: "textures/items/gold_horse_armor.png"},
            {name: "gold_ingot", path: "textures/items/gold_ingot.png"},
            {name: "gold_leggings", path: "textures/items/gold_leggings.png"},
            {name: "gold_nugget", path: "textures/items/gold_nugget.png"},
            {name: "gold_pickaxe", path: "textures/items/gold_pickaxe.png"},
            {name: "gold_shovel", path: "textures/items/gold_shovel.png"},
            {name: "gold_sword", path: "textures/items/gold_sword.png"},
            {name: "gunpowder", path: "textures/items/gunpowder.png"}
        ]
    },
    page9: {
        namespace: "vanilla",
        nextPack: 'vanilla10',
        previousPack: 'vanilla8',
        icons: [
            {name: "guster_banner_pattern", path: "textures/items/guster_banner_pattern.png"},
            {name: "guster_pottery_sherd", path: "textures/items/guster_pottery_sherd.png"},
            {name: "hanging_roots", path: "textures/items/hanging_roots.png"},
            {name: "heartbreak_pottery_sherd", path: "textures/items/heartbreak_pottery_sherd.png"},
            {name: "heartofthesea_closed", path: "textures/items/heartofthesea_closed.png"},
            {name: "heart_pottery_sherd", path: "textures/items/heart_pottery_sherd.png"},
            {name: "hoglin_meat_cooked", path: "textures/items/hoglin_meat_cooked.png"},
            {name: "hoglin_meat_raw", path: "textures/items/hoglin_meat_raw.png"},
            {name: "honeycomb", path: "textures/items/honeycomb.png"},
            {name: "honey_bottle", path: "textures/items/honey_bottle.png"},
            {name: "hopper", path: "textures/items/hopper.png"},
            {name: "host_armor_trim_smithing_template", path: "textures/items/host_armor_trim_smithing_template.png"},
            {name: "howl_pottery_sherd", path: "textures/items/howl_pottery_sherd.png"},
            {name: "iron_axe", path: "textures/items/iron_axe.png"},
            {name: "iron_boots", path: "textures/items/iron_boots.png"},
            {name: "iron_chestplate", path: "textures/items/iron_chestplate.png"},
            {name: "iron_helmet", path: "textures/items/iron_helmet.png"},
            {name: "iron_hoe", path: "textures/items/iron_hoe.png"},
            {name: "iron_horse_armor", path: "textures/items/iron_horse_armor.png"},
            {name: "iron_ingot", path: "textures/items/iron_ingot.png"},
            {name: "iron_leggings", path: "textures/items/iron_leggings.png"},
            {name: "iron_nugget", path: "textures/items/iron_nugget.png"},
            {name: "iron_pickaxe", path: "textures/items/iron_pickaxe.png"},
            {name: "iron_shovel", path: "textures/items/iron_shovel.png"},
            {name: "iron_sword", path: "textures/items/iron_sword.png"},
            {name: "item_frame", path: "textures/items/item_frame.png"},
            {name: "jungle_chest_boat", path: "textures/items/jungle_chest_boat.png"},
            {name: "jungle_hanging_sign", path: "textures/items/jungle_hanging_sign.png"},
            {name: "kelp", path: "textures/items/kelp.png"},
            {name: "lantern", path: "textures/items/lantern.png"},
            {name: "lead", path: "textures/items/lead.png"},
            {name: "leather", path: "textures/items/leather.png"},
            {name: "leather_chestplate", path: "textures/items/leather_chestplate.png"},
            {name: "lever", path: "textures/items/lever.png"},
            {name: "light_block_0", path: "textures/items/light_block_0.png"},
            {name: "light_block_1", path: "textures/items/light_block_1.png"},
            {name: "light_block_10", path: "textures/items/light_block_10.png"},
            {name: "light_block_11", path: "textures/items/light_block_11.png"},
            {name: "light_block_12", path: "textures/items/light_block_12.png"},
            {name: "light_block_13", path: "textures/items/light_block_13.png"},
            {name: "light_block_14", path: "textures/items/light_block_14.png"},
            {name: "light_block_15", path: "textures/items/light_block_15.png"},
            {name: "light_block_2", path: "textures/items/light_block_2.png"},
            {name: "light_block_3", path: "textures/items/light_block_3.png"},
            {name: "light_block_4", path: "textures/items/light_block_4.png"}
        ]
    },
    page10: {
        namespace: "vanilla",
        nextPack: 'vanilla11',
        previousPack: 'vanilla9',
        icons: [
            {name: "light_block_5", path: "textures/items/light_block_5.png"},
            {name: "light_block_6", path: "textures/items/light_block_6.png"},
            {name: "light_block_7", path: "textures/items/light_block_7.png"},
            {name: "light_block_8", path: "textures/items/light_block_8.png"},
            {name: "light_block_9", path: "textures/items/light_block_9.png"},
            {name: "lodestonecompass_atlas", path: "textures/items/lodestonecompass_atlas.png"},
            {name: "lodestonecompass_item", path: "textures/items/lodestonecompass_item.png"},
            {name: "mace", path: "textures/items/mace.png"},
            {name: "magma_cream", path: "textures/items/magma_cream.png"},
            {name: "mangrove_boat", path: "textures/items/mangrove_boat.png"},
            {name: "mangrove_chest_boat", path: "textures/items/mangrove_chest_boat.png"},
            {name: "mangrove_door", path: "textures/items/mangrove_door.png"},
            {name: "mangrove_hanging_sign", path: "textures/items/mangrove_hanging_sign.png"},
            {name: "mangrove_propagule", path: "textures/items/mangrove_propagule.png"},
            {name: "mangrove_sign", path: "textures/items/mangrove_sign.png"},
            {name: "map_empty", path: "textures/items/map_empty.png"},
            {name: "map_filled", path: "textures/items/map_filled.png"},
            {name: "map_locked", path: "textures/items/map_locked.png"},
            {name: "map_mansion", path: "textures/items/map_mansion.png"},
            {name: "map_monument", path: "textures/items/map_monument.png"},
            {name: "map_nautilus", path: "textures/items/map_nautilus.png"},
            {name: "map_trial_chambers", path: "textures/items/map_trial_chambers.png"},
            {name: "melon", path: "textures/items/melon.png"},
            {name: "melon_speckled", path: "textures/items/melon_speckled.png"},
            {name: "minecart_chest", path: "textures/items/minecart_chest.png"},
            {name: "minecart_command_block", path: "textures/items/minecart_command_block.png"},
            {name: "minecart_furnace", path: "textures/items/minecart_furnace.png"},
            {name: "minecart_hopper", path: "textures/items/minecart_hopper.png"},
            {name: "minecart_normal", path: "textures/items/minecart_normal.png"},
            {name: "minecart_tnt", path: "textures/items/minecart_tnt.png"},
            {name: "miner_pottery_sherd", path: "textures/items/miner_pottery_sherd.png"},
            {name: "mojang_banner_pattern", path: "textures/items/mojang_banner_pattern.png"},
            {name: "mourner_pottery_sherd", path: "textures/items/mourner_pottery_sherd.png"},
            {name: "mushroom_stew", path: "textures/items/mushroom_stew.png"},
            {name: "music_disc_creator", path: "textures/items/music_disc_creator.png"},
            {name: "music_disc_creator_music_box", path: "textures/items/music_disc_creator_music_box.png"},
            {name: "music_disc_precipice", path: "textures/items/music_disc_precipice.png"},
            {name: "music_disc_relic", path: "textures/items/music_disc_relic.png"},
            {name: "mutton_cooked", path: "textures/items/mutton_cooked.png"},
            {name: "mutton_raw", path: "textures/items/mutton_raw.png"},
            {name: "name_tag", path: "textures/items/name_tag.png"},
            {name: "nautilus", path: "textures/items/nautilus.png"},
            {name: "netherbrick", path: "textures/items/netherbrick.png"},
            {name: "netherite_axe", path: "textures/items/netherite_axe.png"},
            {name: "netherite_boots", path: "textures/items/netherite_boots.png"}
        ]
    },
    page11: {
        namespace: "vanilla",
        nextPack: 'vanilla12',
        previousPack: 'vanilla10',
        icons: [
            {name: "netherite_chestplate", path: "textures/items/netherite_chestplate.png"},
            {name: "netherite_helmet", path: "textures/items/netherite_helmet.png"},
            {name: "netherite_hoe", path: "textures/items/netherite_hoe.png"},
            {name: "netherite_ingot", path: "textures/items/netherite_ingot.png"},
            {name: "netherite_leggings", path: "textures/items/netherite_leggings.png"},
            {name: "netherite_pickaxe", path: "textures/items/netherite_pickaxe.png"},
            {name: "netherite_scrap", path: "textures/items/netherite_scrap.png"},
            {name: "netherite_shovel", path: "textures/items/netherite_shovel.png"},
            {name: "netherite_sword", path: "textures/items/netherite_sword.png"},
            {name: "netherite_upgrade_smithing_template", path: "textures/items/netherite_upgrade_smithing_template.png"},
            {name: "nether_sprouts", path: "textures/items/nether_sprouts.png"},
            {name: "nether_star", path: "textures/items/nether_star.png"},
            {name: "nether_wart", path: "textures/items/nether_wart.png"},
            {name: "oak_chest_boat", path: "textures/items/oak_chest_boat.png"},
            {name: "oak_hanging_sign", path: "textures/items/oak_hanging_sign.png"},
            {name: "ominous_bottle", path: "textures/items/ominous_bottle.png"},
            {name: "ominous_trial_key", path: "textures/items/ominous_trial_key.png"},
            {name: "oxidized_copper_door", path: "textures/items/oxidized_copper_door.png"},
            {name: "painting", path: "textures/items/painting.png"},
            {name: "pale_oak_boat", path: "textures/items/pale_oak_boat.png"},
            {name: "pale_oak_chest_boat", path: "textures/items/pale_oak_chest_boat.png"},
            {name: "pale_oak_door", path: "textures/items/pale_oak_door.png"},
            {name: "pale_oak_hanging_sign", path: "textures/items/pale_oak_hanging_sign.png"},
            {name: "pale_oak_sign", path: "textures/items/pale_oak_sign.png"},
            {name: "paper", path: "textures/items/paper.png"},
            {name: "phantom_membrane", path: "textures/items/phantom_membrane.png"},
            {name: "piglin_banner_pattern", path: "textures/items/piglin_banner_pattern.png"},
            {name: "pink_petals", path: "textures/items/pink_petals.png"},
            {name: "pitcher_pod", path: "textures/items/pitcher_pod.png"},
            {name: "plenty_pottery_sherd", path: "textures/items/plenty_pottery_sherd.png"},
            {name: "porkchop_cooked", path: "textures/items/porkchop_cooked.png"},
            {name: "porkchop_raw", path: "textures/items/porkchop_raw.png"},
            {name: "potato", path: "textures/items/potato.png"},
            {name: "potato_baked", path: "textures/items/potato_baked.png"},
            {name: "potato_poisonous", path: "textures/items/potato_poisonous.png"},
            {name: "potion_bottle_absorption", path: "textures/items/potion_bottle_absorption.png"},
            {name: "potion_bottle_blindness", path: "textures/items/potion_bottle_blindness.png"},
            {name: "potion_bottle_confusion", path: "textures/items/potion_bottle_confusion.png"},
            {name: "potion_bottle_damageBoost", path: "textures/items/potion_bottle_damageBoost.png"},
            {name: "potion_bottle_digSlowdown", path: "textures/items/potion_bottle_digSlowdown.png"},
            {name: "potion_bottle_digSpeed", path: "textures/items/potion_bottle_digSpeed.png"},
            {name: "potion_bottle_drinkable", path: "textures/items/potion_bottle_drinkable.png"},
            {name: "potion_bottle_empty", path: "textures/items/potion_bottle_empty.png"},
            {name: "potion_bottle_fireResistance", path: "textures/items/potion_bottle_fireResistance.png"},
            {name: "potion_bottle_harm", path: "textures/items/potion_bottle_harm.png"}
        ]
    },
    page12: {
        namespace: "vanilla",
        nextPack: 'vanilla13',
        previousPack: 'vanilla11',
        icons: [
            {name: "potion_bottle_heal", path: "textures/items/potion_bottle_heal.png"},
            {name: "potion_bottle_healthBoost", path: "textures/items/potion_bottle_healthBoost.png"},
            {name: "potion_bottle_hunger", path: "textures/items/potion_bottle_hunger.png"},
            {name: "potion_bottle_infested", path: "textures/items/potion_bottle_infested.png"},
            {name: "potion_bottle_invisibility", path: "textures/items/potion_bottle_invisibility.png"},
            {name: "potion_bottle_jump", path: "textures/items/potion_bottle_jump.png"},
            {name: "potion_bottle_levitation", path: "textures/items/potion_bottle_levitation.png"},
            {name: "potion_bottle_lingering", path: "textures/items/potion_bottle_lingering.png"},
            {name: "potion_bottle_lingering_damageBoost", path: "textures/items/potion_bottle_lingering_damageBoost.png"},
            {name: "potion_bottle_lingering_empty", path: "textures/items/potion_bottle_lingering_empty.png"},
            {name: "potion_bottle_lingering_fireResistance", path: "textures/items/potion_bottle_lingering_fireResistance.png"},
            {name: "potion_bottle_lingering_harm", path: "textures/items/potion_bottle_lingering_harm.png"},
            {name: "potion_bottle_lingering_heal", path: "textures/items/potion_bottle_lingering_heal.png"},
            {name: "potion_bottle_lingering_infested", path: "textures/items/potion_bottle_lingering_infested.png"},
            {name: "potion_bottle_lingering_invisibility", path: "textures/items/potion_bottle_lingering_invisibility.png"},
            {name: "potion_bottle_lingering_jump", path: "textures/items/potion_bottle_lingering_jump.png"},
            {name: "potion_bottle_lingering_luck", path: "textures/items/potion_bottle_lingering_luck.png"},
            {name: "potion_bottle_lingering_moveSlowdown", path: "textures/items/potion_bottle_lingering_moveSlowdown.png"},
            {name: "potion_bottle_lingering_moveSpeed", path: "textures/items/potion_bottle_lingering_moveSpeed.png"},
            {name: "potion_bottle_lingering_nightVision", path: "textures/items/potion_bottle_lingering_nightVision.png"},
            {name: "potion_bottle_lingering_oozing", path: "textures/items/potion_bottle_lingering_oozing.png"},
            {name: "potion_bottle_lingering_poison", path: "textures/items/potion_bottle_lingering_poison.png"},
            {name: "potion_bottle_lingering_regeneration", path: "textures/items/potion_bottle_lingering_regeneration.png"},
            {name: "potion_bottle_lingering_slowFall", path: "textures/items/potion_bottle_lingering_slowFall.png"},
            {name: "potion_bottle_lingering_turtleMaster", path: "textures/items/potion_bottle_lingering_turtleMaster.png"},
            {name: "potion_bottle_lingering_waterBreathing", path: "textures/items/potion_bottle_lingering_waterBreathing.png"},
            {name: "potion_bottle_lingering_weakness", path: "textures/items/potion_bottle_lingering_weakness.png"},
            {name: "potion_bottle_lingering_weaving", path: "textures/items/potion_bottle_lingering_weaving.png"},
            {name: "potion_bottle_lingering_windCharged", path: "textures/items/potion_bottle_lingering_windCharged.png"},
            {name: "potion_bottle_lingering_wither", path: "textures/items/potion_bottle_lingering_wither.png"},
            {name: "potion_bottle_moveSlowdown", path: "textures/items/potion_bottle_moveSlowdown.png"},
            {name: "potion_bottle_moveSpeed", path: "textures/items/potion_bottle_moveSpeed.png"},
            {name: "potion_bottle_nightVision", path: "textures/items/potion_bottle_nightVision.png"},
            {name: "potion_bottle_oozing", path: "textures/items/potion_bottle_oozing.png"},
            {name: "potion_bottle_poison", path: "textures/items/potion_bottle_poison.png"},
            {name: "potion_bottle_regeneration", path: "textures/items/potion_bottle_regeneration.png"},
            {name: "potion_bottle_resistance", path: "textures/items/potion_bottle_resistance.png"},
            {name: "potion_bottle_saturation", path: "textures/items/potion_bottle_saturation.png"},
            {name: "potion_bottle_slowFall", path: "textures/items/potion_bottle_slowFall.png"},
            {name: "potion_bottle_splash", path: "textures/items/potion_bottle_splash.png"},
            {name: "potion_bottle_splash_absorption", path: "textures/items/potion_bottle_splash_absorption.png"},
            {name: "potion_bottle_splash_blindness", path: "textures/items/potion_bottle_splash_blindness.png"},
            {name: "potion_bottle_splash_confusion", path: "textures/items/potion_bottle_splash_confusion.png"},
            {name: "potion_bottle_splash_damageBoost", path: "textures/items/potion_bottle_splash_damageBoost.png"},
            {name: "potion_bottle_splash_digSlowdown", path: "textures/items/potion_bottle_splash_digSlowdown.png"}
        ]
    },
    page13: {
        namespace: "vanilla",
        nextPack: 'vanilla14',
        previousPack: 'vanilla12',
        icons: [
            {name: "potion_bottle_splash_digSpeed", path: "textures/items/potion_bottle_splash_digSpeed.png"},
            {name: "potion_bottle_splash_fireResistance", path: "textures/items/potion_bottle_splash_fireResistance.png"},
            {name: "potion_bottle_splash_harm", path: "textures/items/potion_bottle_splash_harm.png"},
            {name: "potion_bottle_splash_heal", path: "textures/items/potion_bottle_splash_heal.png"},
            {name: "potion_bottle_splash_healthBoost", path: "textures/items/potion_bottle_splash_healthBoost.png"},
            {name: "potion_bottle_splash_hunger", path: "textures/items/potion_bottle_splash_hunger.png"},
            {name: "potion_bottle_splash_infested", path: "textures/items/potion_bottle_splash_infested.png"},
            {name: "potion_bottle_splash_invisibility", path: "textures/items/potion_bottle_splash_invisibility.png"},
            {name: "potion_bottle_splash_jump", path: "textures/items/potion_bottle_splash_jump.png"},
            {name: "potion_bottle_splash_levitation", path: "textures/items/potion_bottle_splash_levitation.png"},
            {name: "potion_bottle_splash_moveSlowdown", path: "textures/items/potion_bottle_splash_moveSlowdown.png"},
            {name: "potion_bottle_splash_moveSpeed", path: "textures/items/potion_bottle_splash_moveSpeed.png"},
            {name: "potion_bottle_splash_nightVision", path: "textures/items/potion_bottle_splash_nightVision.png"},
            {name: "potion_bottle_splash_oozing", path: "textures/items/potion_bottle_splash_oozing.png"},
            {name: "potion_bottle_splash_poison", path: "textures/items/potion_bottle_splash_poison.png"},
            {name: "potion_bottle_splash_regeneration", path: "textures/items/potion_bottle_splash_regeneration.png"},
            {name: "potion_bottle_splash_resistance", path: "textures/items/potion_bottle_splash_resistance.png"},
            {name: "potion_bottle_splash_saturation", path: "textures/items/potion_bottle_splash_saturation.png"},
            {name: "potion_bottle_splash_slowFall", path: "textures/items/potion_bottle_splash_slowFall.png"},
            {name: "potion_bottle_splash_turtleMaster", path: "textures/items/potion_bottle_splash_turtleMaster.png"},
            {name: "potion_bottle_splash_waterBreathing", path: "textures/items/potion_bottle_splash_waterBreathing.png"},
            {name: "potion_bottle_splash_weakness", path: "textures/items/potion_bottle_splash_weakness.png"},
            {name: "potion_bottle_splash_weaving", path: "textures/items/potion_bottle_splash_weaving.png"},
            {name: "potion_bottle_splash_windCharged", path: "textures/items/potion_bottle_splash_windCharged.png"},
            {name: "potion_bottle_splash_wither", path: "textures/items/potion_bottle_splash_wither.png"},
            {name: "potion_bottle_turtleMaster", path: "textures/items/potion_bottle_turtleMaster.png"},
            {name: "potion_bottle_waterBreathing", path: "textures/items/potion_bottle_waterBreathing.png"},
            {name: "potion_bottle_weakness", path: "textures/items/potion_bottle_weakness.png"},
            {name: "potion_bottle_weaving", path: "textures/items/potion_bottle_weaving.png"},
            {name: "potion_bottle_windCharged", path: "textures/items/potion_bottle_windCharged.png"},
            {name: "potion_bottle_wither", path: "textures/items/potion_bottle_wither.png"},
            {name: "potion_overlay", path: "textures/items/potion_overlay.png"},
            {name: "prismarine_crystals", path: "textures/items/prismarine_crystals.png"},
            {name: "prismarine_shard", path: "textures/items/prismarine_shard.png"},
            {name: "prize_pottery_sherd", path: "textures/items/prize_pottery_sherd.png"},
            {name: "pumpkin_pie", path: "textures/items/pumpkin_pie.png"},
            {name: "quartz", path: "textures/items/quartz.png"},
            {name: "quiver", path: "textures/items/quiver.png"},
            {name: "rabbit_cooked", path: "textures/items/rabbit_cooked.png"},
            {name: "rabbit_foot", path: "textures/items/rabbit_foot.png"},
            {name: "rabbit_hide", path: "textures/items/rabbit_hide.png"},
            {name: "rabbit_raw", path: "textures/items/rabbit_raw.png"},
            {name: "rabbit_stew", path: "textures/items/rabbit_stew.png"},
            {name: "raiser_armor_trim_smithing_template", path: "textures/items/raiser_armor_trim_smithing_template.png"},
            {name: "raw_copper", path: "textures/items/raw_copper.png"}
        ]
    },
    page14: {
        namespace: "vanilla",
        nextPack: 'vanilla15',
        previousPack: 'vanilla13',
        icons: [
            {name: "raw_gold", path: "textures/items/raw_gold.png"},
            {name: "raw_iron", path: "textures/items/raw_iron.png"},
            {name: "record_11", path: "textures/items/record_11.png"},
            {name: "record_13", path: "textures/items/record_13.png"},
            {name: "record_5", path: "textures/items/record_5.png"},
            {name: "record_blocks", path: "textures/items/record_blocks.png"},
            {name: "record_cat", path: "textures/items/record_cat.png"},
            {name: "record_chirp", path: "textures/items/record_chirp.png"},
            {name: "record_far", path: "textures/items/record_far.png"},
            {name: "record_mall", path: "textures/items/record_mall.png"},
            {name: "record_mellohi", path: "textures/items/record_mellohi.png"},
            {name: "record_otherside", path: "textures/items/record_otherside.png"},
            {name: "record_pigstep", path: "textures/items/record_pigstep.png"},
            {name: "record_stal", path: "textures/items/record_stal.png"},
            {name: "record_strad", path: "textures/items/record_strad.png"},
            {name: "record_wait", path: "textures/items/record_wait.png"},
            {name: "record_ward", path: "textures/items/record_ward.png"},
            {name: "recovery_compass_atlas", path: "textures/items/recovery_compass_atlas.png"},
            {name: "recovery_compass_item", path: "textures/items/recovery_compass_item.png"},
            {name: "redstone_dust", path: "textures/items/redstone_dust.png"},
            {name: "reeds", path: "textures/items/reeds.png"},
            {name: "repeater", path: "textures/items/repeater.png"},
            {name: "resin_brick", path: "textures/items/resin_brick.png"},
            {name: "resin_clump", path: "textures/items/resin_clump.png"},
            {name: "rib_armor_trim_smithing_template", path: "textures/items/rib_armor_trim_smithing_template.png"},
            {name: "rotten_flesh", path: "textures/items/rotten_flesh.png"},
            {name: "ruby", path: "textures/items/ruby.png"},
            {name: "saddle", path: "textures/items/saddle.png"},
            {name: "scrape_pottery_sherd", path: "textures/items/scrape_pottery_sherd.png"},
            {name: "sea_pickle", path: "textures/items/sea_pickle.png"},
            {name: "seeds_beetroot", path: "textures/items/seeds_beetroot.png"},
            {name: "seeds_melon", path: "textures/items/seeds_melon.png"},
            {name: "seeds_pumpkin", path: "textures/items/seeds_pumpkin.png"},
            {name: "seeds_wheat", path: "textures/items/seeds_wheat.png"},
            {name: "sentry_armor_trim_smithing_template", path: "textures/items/sentry_armor_trim_smithing_template.png"},
            {name: "shaper_armor_trim_smithing_template", path: "textures/items/shaper_armor_trim_smithing_template.png"},
            {name: "sheaf_pottery_sherd", path: "textures/items/sheaf_pottery_sherd.png"},
            {name: "shears", path: "textures/items/shears.png"},
            {name: "shelter_pottery_sherd", path: "textures/items/shelter_pottery_sherd.png"},
            {name: "shulker_shell", path: "textures/items/shulker_shell.png"},
            {name: "sign", path: "textures/items/sign.png"},
            {name: "sign_acacia", path: "textures/items/sign_acacia.png"},
            {name: "sign_birch", path: "textures/items/sign_birch.png"},
            {name: "sign_crimson", path: "textures/items/sign_crimson.png"},
            {name: "sign_darkoak", path: "textures/items/sign_darkoak.png"}
        ]
    },
    page15: {
        namespace: "vanilla",
        nextPack: 'vanilla16',
        previousPack: 'vanilla14',
        icons: [
            {name: "sign_jungle", path: "textures/items/sign_jungle.png"},
            {name: "sign_spruce", path: "textures/items/sign_spruce.png"},
            {name: "sign_warped", path: "textures/items/sign_warped.png"},
            {name: "silence_armor_trim_smithing_template", path: "textures/items/silence_armor_trim_smithing_template.png"},
            {name: "skull_banner_pattern", path: "textures/items/skull_banner_pattern.png"},
            {name: "skull_pottery_sherd", path: "textures/items/skull_pottery_sherd.png"},
            {name: "slimeball", path: "textures/items/slimeball.png"},
            {name: "sniffer_egg", path: "textures/items/sniffer_egg.png"},
            {name: "snort_pottery_sherd", path: "textures/items/snort_pottery_sherd.png"},
            {name: "snout_armor_trim_smithing_template", path: "textures/items/snout_armor_trim_smithing_template.png"},
            {name: "snowball", path: "textures/items/snowball.png"},
            {name: "soul_campfire", path: "textures/items/soul_campfire.png"},
            {name: "soul_lantern", path: "textures/items/soul_lantern.png"},
            {name: "spawn_egg", path: "textures/items/spawn_egg.png"},
            {name: "spawn_egg_overlay", path: "textures/items/spawn_egg_overlay.png"},
            {name: "spider_eye", path: "textures/items/spider_eye.png"},
            {name: "spider_eye_fermented", path: "textures/items/spider_eye_fermented.png"},
            {name: "spire_armor_trim_smithing_template", path: "textures/items/spire_armor_trim_smithing_template.png"},
            {name: "spruce_chest_boat", path: "textures/items/spruce_chest_boat.png"},
            {name: "spruce_hanging_sign", path: "textures/items/spruce_hanging_sign.png"},
            {name: "spyglass", path: "textures/items/spyglass.png"},
            {name: "stick", path: "textures/items/stick.png"},
            {name: "stone_axe", path: "textures/items/stone_axe.png"},
            {name: "stone_hoe", path: "textures/items/stone_hoe.png"},
            {name: "stone_pickaxe", path: "textures/items/stone_pickaxe.png"},
            {name: "stone_shovel", path: "textures/items/stone_shovel.png"},
            {name: "stone_sword", path: "textures/items/stone_sword.png"},
            {name: "string", path: "textures/items/string.png"},
            {name: "sugar", path: "textures/items/sugar.png"},
            {name: "suspicious_stew", path: "textures/items/suspicious_stew.png"},
            {name: "sweet_berries", path: "textures/items/sweet_berries.png"},
            {name: "tide_armor_trim_smithing_template", path: "textures/items/tide_armor_trim_smithing_template.png"},
            {name: "tipped_arrow", path: "textures/items/tipped_arrow.png"},
            {name: "tipped_arrow_base", path: "textures/items/tipped_arrow_base.png"},
            {name: "tipped_arrow_fireres", path: "textures/items/tipped_arrow_fireres.png"},
            {name: "tipped_arrow_harm", path: "textures/items/tipped_arrow_harm.png"},
            {name: "tipped_arrow_head", path: "textures/items/tipped_arrow_head.png"},
            {name: "tipped_arrow_healing", path: "textures/items/tipped_arrow_healing.png"},
            {name: "tipped_arrow_infested", path: "textures/items/tipped_arrow_infested.png"},
            {name: "tipped_arrow_invisibility", path: "textures/items/tipped_arrow_invisibility.png"},
            {name: "tipped_arrow_leaping", path: "textures/items/tipped_arrow_leaping.png"},
            {name: "tipped_arrow_luck", path: "textures/items/tipped_arrow_luck.png"},
            {name: "tipped_arrow_nightvision", path: "textures/items/tipped_arrow_nightvision.png"},
            {name: "tipped_arrow_oozing", path: "textures/items/tipped_arrow_oozing.png"},
            {name: "tipped_arrow_poison", path: "textures/items/tipped_arrow_poison.png"}
        ]
    },
    page16: {
        namespace: "vanilla",
        nextPack: null,
        previousPack: 'vanilla15',
        icons: [
            {name: "tipped_arrow_regen", path: "textures/items/tipped_arrow_regen.png"},
            {name: "tipped_arrow_slow", path: "textures/items/tipped_arrow_slow.png"},
            {name: "tipped_arrow_slowfalling", path: "textures/items/tipped_arrow_slowfalling.png"},
            {name: "tipped_arrow_strength", path: "textures/items/tipped_arrow_strength.png"},
            {name: "tipped_arrow_swift", path: "textures/items/tipped_arrow_swift.png"},
            {name: "tipped_arrow_turtlemaster", path: "textures/items/tipped_arrow_turtlemaster.png"},
            {name: "tipped_arrow_waterbreathing", path: "textures/items/tipped_arrow_waterbreathing.png"},
            {name: "tipped_arrow_weakness", path: "textures/items/tipped_arrow_weakness.png"},
            {name: "tipped_arrow_weaving", path: "textures/items/tipped_arrow_weaving.png"},
            {name: "tipped_arrow_windCharged", path: "textures/items/tipped_arrow_windCharged.png"},
            {name: "tipped_arrow_wither", path: "textures/items/tipped_arrow_wither.png"},
            {name: "torchflower_seeds", path: "textures/items/torchflower_seeds.png"},
            {name: "totem", path: "textures/items/totem.png"},
            {name: "trial_key", path: "textures/items/trial_key.png"},
            {name: "trident", path: "textures/items/trident.png"},
            {name: "turtle_egg", path: "textures/items/turtle_egg.png"},
            {name: "turtle_helmet", path: "textures/items/turtle_helmet.png"},
            {name: "turtle_shell_piece", path: "textures/items/turtle_shell_piece.png"},
            {name: "vex_armor_trim_smithing_template", path: "textures/items/vex_armor_trim_smithing_template.png"},
            {name: "villagebell", path: "textures/items/villagebell.png"},
            {name: "ward_armor_trim_smithing_template", path: "textures/items/ward_armor_trim_smithing_template.png"},
            {name: "warped_door", path: "textures/items/warped_door.png"},
            {name: "warped_fungus_on_a_stick", path: "textures/items/warped_fungus_on_a_stick.png"},
            {name: "warped_hanging_sign", path: "textures/items/warped_hanging_sign.png"},
            {name: "watch_atlas", path: "textures/items/watch_atlas.png"},
            {name: "wayfinder_armor_trim_smithing_template", path: "textures/items/wayfinder_armor_trim_smithing_template.png"},
            {name: "weathered_copper_door", path: "textures/items/weathered_copper_door.png"},
            {name: "wheat", path: "textures/items/wheat.png"},
            {name: "wild_armor_trim_smithing_template", path: "textures/items/wild_armor_trim_smithing_template.png"},
            {name: "wind_charge", path: "textures/items/wind_charge.png"},
            {name: "wolf_armor", path: "textures/items/wolf_armor.png"},
            {name: "wood_axe", path: "textures/items/wood_axe.png"},
            {name: "wood_hoe", path: "textures/items/wood_hoe.png"},
            {name: "wood_pickaxe", path: "textures/items/wood_pickaxe.png"},
            {name: "wood_shovel", path: "textures/items/wood_shovel.png"},
            {name: "wood_sword", path: "textures/items/wood_sword.png"}
        ]
    }
}
export { vanillaPack }